server:
  port: 80

spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://47.107.54.10:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: root_123456

